<?php

namespace AppBundle\Repository;

/**
 * LectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureRepository extends \Doctrine\ORM\EntityRepository
{
}
